version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: oms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: ordermanagementsystem
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - oms-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ordermanagementsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password1
    depends_on:
      - mysql
    networks:
      - oms-network

networks:
  oms-network:

volumes:
  mysql_data:
